//
//  Image.java
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

package com.pinterest.models;

@AutoValue
public abstract class Image {
    public abstract Integer height();
    public abstract URI url();
    public abstract Integer width();
    public static Builder builder() {
        return new AutoValue_Image.Builder();
    }
    abstract Builder toBuilder();
    @AutoValue.Builder
    public abstract class Builder {
        public abstract Builder setHeight(Integer value);
        public abstract Builder setUrl(URI value);
        public abstract Builder setWidth(Integer value);
        public abstract Animal build();
    
    }
}
