//
// Image.java
// Autogenerated by plank
//
// DO NOT EDIT - EDITS WILL BE OVERWRITTEN
// @generated
//

package com.pinterest.models;

import android.support.annotation.IntDef;
import com.google.auto.value.AutoValue;
import java.net.URI;
import java.util.Set;
import android.support.annotation.Nullable;
import android.support.annotation.StringDef;
import java.lang.annotation.Retention;
import java.util.Date;
import java.util.List;
import java.lang.annotation.RetentionPolicy;
import java.util.Map;

public interface ImageModel {
    @SerializedName("height") @Nullable Integer height();
    @SerializedName("url") @Nullable URI url();
    @SerializedName("width") @Nullable Integer width();
}

public interface ImageModelBuilder {
    Builder setHeight(@Nullable Integer value);
    Builder setUrl(@Nullable URI value);
    Builder setWidth(@Nullable Integer value);
}

@AutoValue
public abstract class Image {

    public abstract @SerializedName("height") @Nullable Integer height();
    public abstract @SerializedName("url") @Nullable URI url();
    public abstract @SerializedName("width") @Nullable Integer width();
    public static Builder builder() {
        return new AutoValue_Image.Builder();
    }
    abstract Builder toBuilder();
    @AutoValue.Builder
    public abstract static class Builder {
    
        public abstract Builder setHeight(@Nullable Integer value);
        public abstract Builder setUrl(@Nullable URI value);
        public abstract Builder setWidth(@Nullable Integer value);
        public abstract Image build();
    
    }
}
