//
// Image.java
// Autogenerated by plank
//
// DO NOT EDIT - EDITS WILL BE OVERWRITTEN
// @generated
//

package com.pinterest.models;

import android.support.annotation.IntDef;
import com.google.auto.value.AutoValue;
import java.util.Optional;
import java.util.Set;
import java.net.URI;
import android.support.annotation.StringDef;
import java.lang.annotation.Retention;
import java.util.Date;
import java.util.List;
import java.lang.annotation.RetentionPolicy;
import java.util.Map;

public interface ImageModel {
    Optional<Integer> height();
    Optional<URI> url();
    Optional<Integer> width();
}

public interface ImageModelBuilder {
    Builder setHeight(Optional<Integer> value);
    Builder setUrl(Optional<URI> value);
    Builder setWidth(Optional<Integer> value);
    Builder setHeight(Integer value);
    Builder setUrl(URI value);
    Builder setWidth(Integer value);
}

@AutoValue
public abstract class Image {

    public abstract Optional<Integer> height();
    public abstract Optional<URI> url();
    public abstract Optional<Integer> width();
    public static Builder builder() {
        return new AutoValue_Image.Builder();
    }
    abstract Builder toBuilder();
    @AutoValue.Builder
    public abstract static class Builder {
    
        public abstract Builder setHeight(Optional<Integer> value);
        public abstract Builder setUrl(Optional<URI> value);
        public abstract Builder setWidth(Optional<Integer> value);
        public abstract Builder setHeight(Integer value);
        public abstract Builder setUrl(URI value);
        public abstract Builder setWidth(Integer value);
        public abstract Image build();
    
    }
}
