//
//  User.java
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

package com.pinterest.models;

import com.google.auto.value.AutoValue;

@AutoValue
public abstract class User {
    public abstract Optional<String> lastName();
    public abstract Optional<String> identifier();
    public abstract Optional<String> firstName();
    public abstract Optional<Image> image();
    public abstract Optional<Map<String, Integer>> counts();
    public abstract Optional<Date> createdAt();
    public abstract Optional<String> username();
    public abstract Optional<String> bio();
    public static Builder builder() {
        return new AutoValue_User.Builder();
    }
    abstract Builder toBuilder();
    @AutoValue.Builder
    public abstract class Builder {
        public abstract Builder setLastName(Optional<String> value);
        public abstract Builder setIdentifier(Optional<String> value);
        public abstract Builder setFirstName(Optional<String> value);
        public abstract Builder setImage(Optional<Image> value);
        public abstract Builder setCounts(Optional<Map<String, Integer>> value);
        public abstract Builder setCreatedAt(Optional<Date> value);
        public abstract Builder setUsername(Optional<String> value);
        public abstract Builder setBio(Optional<String> value);
        public abstract Builder setLastName(String value);
        public abstract Builder setIdentifier(String value);
        public abstract Builder setFirstName(String value);
        public abstract Builder setImage(Image value);
        public abstract Builder setCounts(Map<String, Integer> value);
        public abstract Builder setCreatedAt(Date value);
        public abstract Builder setUsername(String value);
        public abstract Builder setBio(String value);
        public abstract Animal build();
    
    }
}
