//  @flow
//
//  PinType.js
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

import type { PlankDate, PlankURI } from './runtime.flow.js';
import type { BoardType } from './BoardType.js';
import type { ImageType } from './ImageType.js';
import type { UserType } from './UserType.js';

export type PinAttributionObjectsType = BoardType | UserType;

export type PinInStockType = 
  | -1 /* unknown */
  | 0 /* out_of_stock */
  | 1 /* in_stock */
;

export type PinType = $Shape<{|
  +note: ?string,
  +media: ?{ +[string]: string },
  +counts: ?{ +[string]: number } /* Integer */,
  +description: ?string,
  +creator: { +[string]: UserType },
  +in_stock: PinInStockType,
  +attribution: ?{ +[string]: string },
  +tags: ?Array<{}>,
  +visual_search_attrs: ?{},
  +board: ?BoardType,
  +link: ?PlankURI,
  +color: ?string,
  +id: string,
  +image: ?ImageType,
  +created_at: PlankDate,
  +attribution_objects: ?Array<PinAttributionObjectsType>,
  +url: ?PlankURI,
|}> & {
  id: string
};

